# Generated by Django 5.0.2 on 2024-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_todolist_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='perfect',
            field=models.IntegerField(default=0),
        ),
    ]
