# Generated by Django 5.0.2 on 2024-04-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0005_alter_todolist_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoList.subjects'),
        ),
    ]
