# Generated by Django 5.0.2 on 2024-04-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0006_alter_todolist_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='subject',
            new_name='Subject_Code',
        ),
    ]
