# Generated by Django 5.0.2 on 2024-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0007_rename_subject_todolist_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
