# Generated by Django 5.0.2 on 2024-04-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0009_todolist_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='users',
        ),
    ]
