# Generated by Django 5.0.2 on 2024-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0013_remove_subjects_end_time_remove_subjects_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='task_type',
            field=models.CharField(choices=[('activity', 'Activity'), ('quiz', 'Quiz')], default='activity', max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectschedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
    ]
