# Generated by Django 5.0.2 on 2024-05-02 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0014_todolist_task_type_alter_subjectschedule_day_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='users',
        ),
        migrations.AddField(
            model_name='subjects',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='enrolled_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjects',
            name='teacher',
            field=models.OneToOneField(default=None, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taught_subject', to=settings.AUTH_USER_MODEL),
        ),
    ]
