# Generated by Django 5.0.2 on 2024-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0018_remove_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
