# Generated by Django 5.0.2 on 2024-04-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
