# Generated by Django 5.0.2 on 2024-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('CIVE', 'Civil Engineering'), ('MECE', 'Mechanical Engineering'), ('ELEC', 'Electrical Engineering'), ('ELEN', 'Electronics Engineering'), ('COEN', 'Computer Engineering'), ('CHEN', 'Chemical Engineering'), ('COMP', 'Computer Science'), ('INFT', 'Information Technology'), ('INSY', 'Information Systems'), ('ARCH', 'Architecture'), ('INDE', 'Interior Design'), ('INDD', 'Industrial Design'), ('FNAR', 'Fine Arts'), ('BSAD', 'Business Administration'), ('ACCY', 'Accountancy'), ('MANA', 'Management'), ('MARK', 'Marketing'), ('ECON', 'Economics'), ('EEED', 'Elementary Education'), ('SEED', 'Secondary Education'), ('SPED', 'Special Education'), ('ENGL', 'English'), ('MATH', 'Mathematics'), ('PSYC', 'Psychology'), ('BIOL', 'Biology'), ('CHEM', 'Chemistry'), ('PHYS', 'Physics'), ('COMM', 'Communication'), ('NURS', 'Nursing'), ('MEDT', 'Medical Technology'), ('PHAR', 'Pharmacy'), ('PHYT', 'Physical Therapy'), ('MARE', 'Marine Engineering'), ('MART', 'Marine Transportation')], max_length=4, null=True),
        ),
    ]
